### ISSUE TITLE
python 2 support

### ISSUE THREAD

**Issue by paulbrodersen** [Penlect/rectangle-packer#1]
Awesome work. Works beautifully only that I couldn't get the package (downloaded from pip) to work in a python 2 environment. Not saying that you should support python 2, but maybe add a warning to the README. 

---

Also, if you want to add some more pretty pictures to stimulate people's imagination of what can be done with this package, I just made this using `rpack`: 
https://stackoverflow.com/a/53156709/2912349

You have a criminally low star/fork count for something so useful.

**Comment by Penlect** [comment]
Hi Paul,

Thank you very much for your feedback! Made me really happy. I updated the readme file to notify that only Python 3 is supported and also embedded a link to your fantastic image in the examples section. I am very happy that you found the package useful.

Cheers,
Daniel

**Comment by paulbrodersen** [comment]
Keep up the good work!
