### ISSUE TITLE
manylinux `aarch64` wheels missing for py310

### ISSUE THREAD

**Issue by randomir** [Penlect/rectangle-packer#16]
Latest [version](https://pypi.org/project/rectangle-packer/#files) does not ship arm64 wheels for python 3.10 (but it does for python 3.6-3.9).

**Comment by Penlect** [comment]
Hi, sorry for the delay, thanks for pointing this out. I have built and uploaded all wheels that `cibuildwheel` was able to produce on my amd64 debian machine.

**Comment by randomir** [comment]
Excellent, thank you! Even musllinux wheels, nice!
