### ISSUE TITLE
Add support for positive float numbers

### ISSUE THREAD

**Issue by tigrus** [Penlect/rectangle-packer#3]
Hi. Thanks for great work. 

Can we add support for positive float in `rpack.pack` method?

**Comment by Penlect** [comment]
Hi, thank you!

I believe the best approach is to multiply your floats 3.14, 2.72 and 0.62 (for example) with 100 to convert them to integers 314, 272, 62, and then do the packing, and finally divide the result with 100 to get the floats back.
